"""add code_snapshots

Revision ID: 5ba13825029a
Revises: cc56d0317297
Create Date: 2026-07-05 11:25:25.005448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba13825029a'
down_revision: Union[str, None] = 'cc56d0317297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('execution_event_id', sa.String(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('diff_stats', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_snapshots_session_id'), 'code_snapshots', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_snapshots_session_id'), table_name='code_snapshots')
    op.drop_table('code_snapshots')
    # ### end Alembic commands ###
