"""baseline schema

Revision ID: aec98a2da8c1
Revises: 
Create Date: 2026-07-05 11:00:19.488924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec98a2da8c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_scores',
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('capability', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('events_count', sa.Integer(), nullable=False),
    sa.Column('last_event_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('student_id', 'capability')
    )
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('capability', sa.String(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('polarity', sa.String(), nullable=False),
    sa.Column('producer', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_capability'), 'events', ['capability'], unique=False)
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_index(op.f('ix_events_student_id'), 'events', ['student_id'], unique=False)
    op.create_table('execution_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('pattern_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('error_family', sa.String(), nullable=True),
    sa.Column('knowledge_points', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_events_pattern_id'), 'execution_events', ['pattern_id'], unique=False)
    op.create_index(op.f('ix_execution_events_session_id'), 'execution_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_execution_events_student_id'), 'execution_events', ['student_id'], unique=False)
    op.create_table('knowledge_states',
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('pattern_id', sa.String(), nullable=False),
    sa.Column('knowledge_points', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('student_id', 'pattern_id')
    )
    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_table('tutor_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('pattern_id', sa.String(), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('hint_level', sa.String(), nullable=False),
    sa.Column('mine_status', sa.String(), nullable=False),
    sa.Column('attribution_step', sa.String(), nullable=False),
    sa.Column('internalize_scores', sa.JSON(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('stalled_turns', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_sessions_student_id'), 'tutor_sessions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_sessions_student_id'), table_name='tutor_sessions')
    op.drop_table('tutor_sessions')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.drop_table('students')
    op.drop_table('knowledge_states')
    op.drop_index(op.f('ix_execution_events_student_id'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_session_id'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_pattern_id'), table_name='execution_events')
    op.drop_table('execution_events')
    op.drop_index(op.f('ix_events_student_id'), table_name='events')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_index(op.f('ix_events_capability'), table_name='events')
    op.drop_table('events')
    op.drop_table('capability_scores')
    # ### end Alembic commands ###
