"""add tutor_sessions.updated_at

Revision ID: cc56d0317297
Revises: aec98a2da8c1
Create Date: 2026-07-05 11:02:37.049673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc56d0317297'
down_revision: Union[str, None] = 'aec98a2da8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 加 nullable 列（SQLite 无法给已有行的 NOT NULL 新列补默认值），再把存量行回填成 created_at
    # ——这些老会话没有活动时间记录，用创建时间作为初始「最近活动」用于排序，之后被 touch() 刷新。
    op.add_column('tutor_sessions', sa.Column('updated_at', sa.String(), nullable=True))
    op.execute("UPDATE tutor_sessions SET updated_at = created_at WHERE updated_at IS NULL")
    op.create_index(op.f('ix_tutor_sessions_updated_at'), 'tutor_sessions', ['updated_at'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_sessions_updated_at'), table_name='tutor_sessions')
    op.drop_column('tutor_sessions', 'updated_at')
    # ### end Alembic commands ###
