"""add student_experiences

Revision ID: d8a4d2cf8080
Revises: e4a9c7d21f30
Create Date: 2026-07-15 22:42:37.208378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a4d2cf8080'
down_revision: Union[str, None] = 'e4a9c7d21f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_experiences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('pattern_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_experiences_pattern_id'), 'student_experiences', ['pattern_id'], unique=False)
    op.create_index(op.f('ix_student_experiences_student_id'), 'student_experiences', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_experiences_student_id'), table_name='student_experiences')
    op.drop_index(op.f('ix_student_experiences_pattern_id'), table_name='student_experiences')
    op.drop_table('student_experiences')
    # ### end Alembic commands ###
